### ISSUE TITLE
Should we make our ID Notes harder to miss?

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#94]
We got one of our first instances of [in-the-wild use](https://www.inaturalist.org/observations/1947007) today, and it suggested a minor potential issue with the current setup. 

Steve Jones found the page I just made for [Atrusca bella ](https://www.gallformers.org/gall/759) and confirmed that the observation matched the description. Great! What he doesn't seem to have noticed is the note I wrote, which explains that this species is not distinguishable from several similar species without rearing an adult. 

These notes are our only novel content and in many cases will be the most useful info users need to confirm their ID against other possibilities. But it probably isn't obvious to many people why they should click on "Various authors. Gallformers.org" or what they should expect to see there.  

For now, I'm just going to change the Citation field to something more informative. But in the long term, should we think about a different way to make these notes more salient and distinct from the other sources?

**Comment by jeffdc** [comment]
Hmmm, yeah I can see the issue. Maybe we should have a separate field from the source descriptions that contains our own content as well as highlighting any gotchas like with this species.

**Comment by Megachile** [comment]
I agree. I think it would make sense that the default presentation should show one of the sources that gives a basic description of the gall on its own, and our ID notes--in the majority of cases, that should be enough but not too little to make an informed ID.

**Comment by madeleineclaire** [comment]
I'm all about this. It seems more user-friendly both to the front end user trying to ID the gall and the back end user trying to make the description in the linked sources more palatable to a front end user. When adding my first two galls to the database I got hung up on the description field quite a bit as at first I didn't realize it was source-specific rather than an overall description summary for the gall.

**Comment by Megachile** [comment]
It was never my intention to have our users write new descriptions of the galls per se. My thought with the ID notes was to supplement with taxonomic and comparative context that wasn't apparent in the other sources. No reason we can't let users do it (feel free) but it's not something I would expect to be done for the majority of galls.

**Comment by jeffdc** [comment]
The primary purpose of the site is to help people ID what they find, secondarily it is a reference tool for pursuing further information. To this end, I believe that most every gall entry would have an "ID section" written by one of us. I still think we can use the Source like we are now from the admin side, but I am thinking that as part of #165 we should also rethink how we display "Gallformer Contributor Notes".

**Comment by Megachile** [comment]
I have no objection to people doing that or setting it as an aspiration but it's not something I feel qualified to write for many species myself, and it doesn't necessarily seem like a great use of time to paraphrase/synthesize sources on species I'm not very familiar with.

**Comment by Megachile** [comment]
I'm also slightly concerned that inviting users to write those would create information we can't vouch for.

**Comment by jeffdc** [comment]
I think that the average user is going to use it like a Field Guide. This is especially true on the ID page. User behavior on web applications, regardless of the purpose of the app, is to not click into too many details. My educated guess as to the percentages of use would be like this:

- 90% of users start on the ID tool (they do not know the name of the gall already)
- 20% get confused by the ID page/have no idea about the host/are scared of latin/... and leave
- of the remaining 80%, they find some galls, 50% read the blurbs and pick one without ever clicking through
- of the remaining 36% (90% * 80% * 50%), 75% of them will never select another source beyond the default
- final tally: 9% of users get to the gall page and switch sources
- if you add in the case of directly navigating to a gall page (e.g., a shared link on iNat) that 75% number still applies

I could be wrong, but instinct and seeing how people use web apps tells me I am not.

We (all of us in the Slack group) are in that final 9%, or to be more generous, 25%. I think that we must take this into consideration as we think about how we design the "happy path" flows through the system.

I agree with you that there is danger in summarization without direct knowledge and I am not advocating for bad summaries. It is a hard problem for sure, but I think that our goal with admin users, is to have people that are generally competent in general and in more particular expert/dedicated amateur in specific areas.

**Comment by Megachile** [comment]
I'm not sure what changes that might entail re: this issue. What you're proposing seems like it would be perfectly addressed by the current build. A user could write a descriptive summary in the ID Notes source and tag it as default, and the original issue wouldn't apply since the best description and any other notes would appear in the same, default entry. 

But whether we make a concerted effort to add our own descriptions where possible or not, many entries will inevitably be in the opposite situation for a long time, with some often-crucial ID info in our notes but the best description in a primary source, requiring the user to click through from one to the other. Is that something we could/want to change the page to address? 

What I'm imagining here is a part of the page (however it was inputted, as a new special source or a separate field on the gall page or whatever) that would display between the traits box and the default source, that would just contain this kind of crucial info (preferably short). Other suggestions welcome. Otherwise I'm not sure this issue needs to stay open.

**Comment by jeffdc** [comment]
One approach to this is to make the "Gallformers Contributors" (hence forth GC) source take precedence as the default if it is present. This is the simplest approach.

Another approach is to not make the GC source part of the Further Information table and instead put the description in above the selected source selection. This would make it always visible if it is present and push the other descriptions down the page. If we did this I would probably rethink how the Further Info table works and move the descriptions to be more inline with the selected source (if possible). On species like this: http://localhost:3000/gall/581 the long GC source description would push the other stuff way down the page. I could make the GC source collapsible but that would, obviously, require user action.

I think this boils down to the larger discussion we had above and the overall intent of the GC Source.

**Comment by Megachile** [comment]
I think that aligns with my suggestion above: we make a second GC "source" that is, as you describe, always visible on top of the existing default source, while the normal ID Notes would remain just one of many sources, which could be the default but isn't necessarily. The priority source would always be short, so it wouldn't exacerbate the pushing issue much beyond what it is now.

**Comment by Megachile** [comment]
So I just talked this over with @ahiatt14 and he came up with a proposal that would require minimal changes to the current source system.

### Proposal

- If no ID notes, display Default or oldest source as currently
- If ID notes is selected as default, display it alone, as currently
- If ID notes exists but another source is selected as default, display a new colored text alert box between the gall info box and the displayed source that reads something to the effect of "Our ID Notes may have important information about the taxonomic status and identification issues for this gall; click here to read them" and include a link that switches from the default source to the ID Notes.

Thoughts?

**Comment by jeffdc** [comment]
This would work. Though it will still not allow us to link to specific descriptions which is something that I frequently wish we could do.

**Comment by Megachile** [comment]
Yep this is a surgical change designed to address just this one issue in the most simple and direct way possible. Sounds like that's what we're looking for at the moment.
